#!/bin/python3

import math
import os
import random
import re
import sys
if __name__ == '__main__':
    s = input()
    s = sorted(s)

    freq = {}

    for letter in s:
        if letter in freq:
            freq[letter] += 1
        else:
            freq[letter] = 1

    freq_sorted = sorted(freq.items(), key=lambda x: (-x[1], x[0]))

    for k, v in freq_sorted[:3]:
        print(k, v)

        
